import {FormFieldTypes, OptionType, WidthType} from "@/types/forms";
import {AmazonPrepHints} from "@/screens/AmazonPrepPage/amazonPrepHints.constants";
import {OrdersTenantDataType} from "@/lib/tenants";

export const GeneralFields = (newObject, orderTitles: OrdersTenantDataType) => [
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'wapiTrackingNumber',
        label: orderTitles.trackingNumberTitle || 'Warehouse tracking number',
        placeholder: "",
        disabled: true,
        width: WidthType.w25,
        classNames: "",
        isDisplayed: !newObject,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'status',
        label: "Status",
        placeholder: "",
        disabled: true,
        width: WidthType.w25,
        classNames: "",
        isDisplayed: !newObject,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'statusAdditionalInfo',
        label: "Status additional info",
        placeholder: "",
        disabled: true,
        width: WidthType.w50,
        classNames: "",
        isDisplayed: !newObject,
    },
    {
        fieldType: FormFieldTypes.DATE,
        type: "date",
        name: 'date',
        label: "Order date",
        placeholder: "",
        width: WidthType.w25,
        classNames: "",
        hint: AmazonPrepHints['date'] || '',
    },
    {
        fieldType: FormFieldTypes.DATE,
        type: "date",
        name: 'preferredDeliveryDate',
        label: "Preferred delivery date",
        placeholder: "",
        width: WidthType.w25,
        classNames: "",
        hint: AmazonPrepHints['preferredDeliveryDate'] || '',
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'clientOrderID',
        label: "Order ID",
        placeholder: "",
        width: WidthType.w50,
        classNames: "",
        hint: AmazonPrepHints['clientOrderID'] || '',
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'comment',
        label: 'Comment for warehouse',
        placeholder: "",
        width: WidthType.w100,
        classNames: "",
        hint: AmazonPrepHints['comment'] || '',
    },
];

export const DetailsFields = ({newObject, warehouses, courierServices, handleWarehouseChange,linkToTrack,deliveryMethodOptions,  carrierTypeOptions, multipleLocations=false}:{newObject:boolean, warehouses: OptionType[], courierServices: OptionType[], handleWarehouseChange:(w: string)=>void,linkToTrack:any; deliveryMethodOptions: OptionType[];  carrierTypeOptions: OptionType[]; multipleLocations?: boolean;}) => [
    {
        name: 'grid-11',
        fieldType: FormFieldTypes.GRID,
        width: WidthType.w50,
        fields: [{
            fieldType: FormFieldTypes.TEXT,
            type: "text",
            name: 'asnNumber',
            label: 'ASN',
            placeholder: "",
            rules: {
                required: "Required field",
            },
            width: WidthType.autoGrow,
            classNames: "",
            hint: AmazonPrepHints['asnNumber'] || '',
        },
        {
            fieldType:FormFieldTypes.RADIO,
            name: 'deliveryMethod',
            options: deliveryMethodOptions,
            width: WidthType.autoNoGrow,
            hint: AmazonPrepHints['deliveryMethod'] || '',
        }]
    },
    {
        fieldType: FormFieldTypes.GRID,
        name: 'grid-2',
        isGrid: true,
        width: WidthType.w50,
        fields: [
            {
                fieldType:FormFieldTypes.RADIO,
                name: 'carrierType',
                options: carrierTypeOptions,
                width: WidthType.autoNoGrow,
                //classNames: 'flex-auto',
                hint: AmazonPrepHints['carrierType'] || '',
            },
            //
            // {
            //     fieldType: FormFieldTypes.TOGGLE,
            //     name: 'prepackedMasterBox',
            //     label: "Prepacked",
            //     width: WidthType.autoGrow,
            //     classNames: '',
            // //disabled: multipleLocations,
            // }
        ]
    },
    {
        fieldType: FormFieldTypes.SELECT,
        type: "text",
        name: 'warehouse',
        label: 'Warehouse',
        placeholder: "",
        rules: {
            required: "Required field",
        },
        options: warehouses,
        width: WidthType.w50,
        //onChange: handleWarehouseChange,
        classNames: "",
        hint: AmazonPrepHints['warehouse'] || '',
    },
    {
        fieldType: FormFieldTypes.SELECT,
        type: "text",
        name: 'courierService',
        label: 'Courier service',
        placeholder: "",
        options: courierServices,
        width: WidthType.w50,
        classNames: "",
        disabled: true, //carrierDisabled,
        hint: AmazonPrepHints['courierService'] || '',
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'courierServiceTrackingNumber',
        label: 'Tracking number',
        placeholder: "",
        disabled: true,
        width: WidthType.w25,
        classNames: "",
        hint: AmazonPrepHints['courierServiceTrackingNumber'] || '',
    },
    {
        fieldType: FormFieldTypes.OTHER,
        name: 'trackingLink',
        label: 'Tracking link',
        otherComponent: linkToTrack,
        width: WidthType.w75,
        classNames: 'amazon-tracking-link',
        hint: AmazonPrepHints['trackingLink'] || '',
        isDisplayed: !newObject,
    },
];

export const ReceiverFields = ({countries, multipleLocations=false}: { countries: OptionType[]; multipleLocations?: boolean;}) => [
    {
        fieldType: FormFieldTypes.TOGGLE,
        name: 'multipleLocations',
        label: "Multiple locations",
        width: WidthType.w100,
        classNames: "",
        hint: AmazonPrepHints['multipleLocations'] || '',
    },
    {
        fieldType: FormFieldTypes.SELECT,
        type: "text",
        name: 'receiverCountry',
        label: 'Country',
        placeholder: "",
        options: countries,
        rules: {
            required: multipleLocations ? false : "Required field",
        },
        errorMessage: "Required field",
        width: WidthType.w25,
        classNames: "",
        disabled: multipleLocations,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'receiverCity',
        label: 'City',
        placeholder: "",
        rules: {
            required: multipleLocations ? false : "Required field",
        },
        errorMessage: "Required field",
        width: WidthType.w25,
        classNames: "",
        disabled: multipleLocations,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'receiverZip',
        label: 'Zip',
        placeholder: "",
        rules:  {
            required: multipleLocations ? false : "Required field",
        },
        errorMessage: "Required field",
        width: WidthType.w17,
        classNames: "",
        disabled: multipleLocations,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'receiverAddress',
        label: 'Address',
        placeholder: "",
        rules: {
            required: multipleLocations ? false : "Required field",
        },
        errorMessage: "Required field",
        width: WidthType.w33,
        classNames: "",
        disabled: multipleLocations,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'receiverPhone',
        label: 'Phone',
        placeholder: "",
        // rules: {
        //     required: "Required field",
        // },
        errorMessage: "Required field",
        width: WidthType.w25,
        classNames: "",
        disabled: multipleLocations,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'receiverEMail',
        label: 'E-mail',
        placeholder: "",
        rules: {
            validate: {
                matchPattern: (v) =>
                    v==='' || /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(v) ||
                    "Please, enter valid email address",
            },
        },
        errorMessage: "Required field",
        width: WidthType.w25,
        classNames: "",
        needToasts: false,
        disabled: multipleLocations,
    },
    {
        fieldType: FormFieldTypes.TEXT,
        type: "text",
        name: 'receiverFullName',
        label: 'Full name',
        placeholder: "",
        rules: {
            required: multipleLocations ? false : "Required field",
        },
        errorMessage: "Required field",
        width: WidthType.w50,
        classNames: "",
        disabled: multipleLocations,
    },
    // {
    //     fieldType: FormFieldTypes.TEXT,
    //     type: "text",
    //     name: 'receiverComment',
    //     label: 'Comment',
    //     placeholder: "",
    //     width: WidthType.w100,
    //     classNames: "",
    //     disabled: multipleLocations,
    // },
];

