export enum Countries {
  AF = "Afghanistan",
  AX = "AlandIslands",
  AL = "Albania",
  DZ = "Algeria",
  AS = "American Samoa",
  AD = "Andorra",
  AO = "Angola",
  AI = "Anguilla",
  AQ = "Antarctica",
  AG = "Antigua and Barbuda",
  AR = "Argentina",
  AM = "Armenia",
  AW = "Aruba",
  AU = "Australia",
  AT = "Austria",
  AZ = "Azerbaijan",
  BS = "Bahamas",
  BH = "Bahrain",
  BD = "Bangladesh",
  BB = "Barbados",
  BY = "Belarus",
  BE = "Belgium",
  BZ = "Belize",
  BJ = "Benin",
  BM = "Bermuda",
  BT = "Bhutan",
  BO = "Bolivia",
  BA = "Bosnia and Herzegovina",
  BW = "Botswana",
  BV = "Bouvet Island",
  BR = "Brazil",
  IO = "British Indian Ocean Territory",
  BN = "Brunei Darussalam",
  BG = "Bulgaria",
  BF = "Burkina Faso",
  BI = "Burundi",
  KH = "Cambodia",
  CM = "Cameroon",
  CA = "Canada",
  CV = "Cape Verde",
  KY = "Cayman Islands",
  CF = "Central African Republic",
  TD = "Chad",
  CL = "Chile",
  CN = "China",
  CX = "Christmas Island",
  CC = "Cocos Keeling Islands",
  CO = "Colombia",
  KM = "Comoros",
  CG = "Congo",
  CD = "Congo Democratic Republic",
  CK = "Cook Islands",
  CR = "Costa Rica",
  CI = "CoteDIvoire",
  HR = "Croatia",
  CU = "Cuba",
  CW = "Curaçao",
  CY = "Cyprus",
  CZ = "Czech Republic",
  DK = "Denmark",
  DJ = "Djibouti",
  DM = "Dominica",
  DO = "Dominican Republic",
  EC = "Ecuador",
  EG = "Egypt",
  SV = "El Salvador",
  GQ = "Equatorial Guinea",
  ER = "Eritrea",
  EE = "Estonia",
  ET = "Ethiopia",
  FK = "Falkland Islands",
  FO = "Faroe Islands",
  FJ = "Fiji",
  FI = "Finland",
  FR = "France",
  GF = "French Guiana",
  PF = "French Polynesia",
  TF = "French Southern Territories",
  GA = "Gabon",
  GM = "Gambia",
  GE = "Georgia",
  DE = "Germany",
  GH = "Ghana",
  GI = "Gibraltar",
  GR = "Greece",
  GL = "Greenland",
  GD = "Grenada",
  GP = "Guadeloupe",
  GU = "Guam",
  GT = "Guatemala",
  GG = "Guernsey",
  GN = "Guinea",
  GW = "Guinea Bissau",
  GY = "Guyana",
  HT = "Haiti",
  HM = "Heard Island Mcdonald Islands",
  VA = "Holy See Vatican City State",
  HN = "Honduras",
  HK = "HongKong",
  HU = "Hungary",
  IS = "Iceland",
  IN = "India",
  ID = "Indonesia",
  IR = "Iran",
  IQ = "Iraq",
  IE = "Ireland",
  IM = "Isle Of Man",
  IL = "Israel",
  IT = "Italy",
  JM = "Jamaica",
  JP = "Japan",
  JE = "Jersey",
  JO = "Jordan",
  KZ = "Kazakhstan",
  KE = "Kenya",
  KI = "Kiribati",
  KR = "Korea, Republic of",
  KP = "Korea, Democratic People's Republic of",
  KW = "Kuwait",
  KG = "Kyrgyzstan",
  LA = "Lao Peoples Democratic Republic",
  LV = "Latvia",
  LB = "Lebanon",
  LS = "Lesotho",
  LR = "Liberia",
  LY = "Libyan Arab Jamahiriya",
  LI = "Liechtenstein",
  LT = "Lithuania",
  LU = "Luxembourg",
  MO = "Macao",
  MG = "Madagascar",
  MW = "Malawi",
  MY = "Malaysia",
  MV = "Maldives",
  ML = "Mali",
  MT = "Malta",
  MH = "Marshall Islands",
  MQ = "Martinique",
  MR = "Mauritania",
  MU = "Mauritius",
  YT = "Mayotte",
  MX = "Mexico",
  FM = "Micronesia",
  MD = "Moldova",
  MC = "Monaco",
  MN = "Mongolia",
  ME = "Montenegro",
  MS = "Montserrat",
  MA = "Morocco",
  MZ = "Mozambique",
  MM = "Myanmar",
  NA = "Namibia",
  NR = "Nauru",
  NP = "Nepal",
  NL = "Netherlands",
  NC = "New Caledonia",
  NZ = "New Zealand",
  NI = "Nicaragua",
  NE = "Niger",
  NG = "Nigeria",
  NU = "Niue",
  NF = "Norfolk Island",
  MP = "Northern Mariana Islands",
  NO = "Norway",
  OM = "Oman",
  PK = "Pakistan",
  PW = "Palau",
  PS = "Palestinian Territory",
  PA = "Panama",
  PG = "Papua New Guinea",
  PY = "Paraguay",
  PE = "Peru",
  PH = "Philippines",
  PN = "Pitcairn",
  PL = "Poland",
  PT = "Portugal",
  PR = "Puerto Rico",
  QA = "Qatar",
  RE = "Reunion",
  MKD = "Republic of North Macedonia",
  RO = "Romania",
  RU = "Russian Federation",
  RW = "Rwanda",
  BL = "Saint Barthelemy",
  SH = "Saint Helena",
  KN = "Saint Kitts And Nevis",
  LC = "Saint Lucia",
  MF = "Saint Martin",
  PM = "Saint Pierre And Miquelon",
  VC = "Saint Vincent And Grenadines",
  WS = "Samoa",
  SM = "San Marino",
  ST = "Sao Tome And Principe",
  SA = "Saudi Arabia",
  SN = "Senegal",
  RS = "Serbia",
  SC = "Seychelles",
  SL = "Sierra Leone",
  SG = "Singapore",
  SK = "Slovakia",
  SI = "Slovenia",
  SB = "Solomon Islands",
  SO = "Somalia",
  ZA = "South Africa",
  GS = "South Georgia And Sandwich Island",
  ES = "Spain",
  LK = "Sri Lanka",
  SD = "Sudan",
  SS = "South Sudan",
  SR = "Suriname",
  SJ = "Svalbard And Jan Mayen",
  SZ = "Swaziland",
  SE = "Sweden",
  CH = "Switzerland",
  SX = "Sint Maarten (Dutch part",
  SY = "Syrian Arab Republic",
  TW = "Taiwan",
  TJ = "Tajikistan",
  TZ = "Tanzania",
  TH = "Thailand",
  TL = "TimorLeste",
  TG = "Togo",
  TK = "Tokelau",
  TO = "Tonga",
  TT = "Trinidad And Tobago",
  TN = "Tunisia",
  TR = "Turkey",
  TM = "Turkmenistan",
  TC = "Turks And Caicos Islands",
  TV = "Tuvalu",
  UG = "Uganda",
  UA = "Ukraine",
  AE = "United Arab Emirates",
  GB = "United Kingdom",
  US = "United States",
  UM = "United States Outlying Islands",
  UY = "Uruguay",
  UZ = "Uzbekistan",
  VU = "Vanuatu",
  VE = "Venezuela",
  VN = "Vietnam",
  VG = "Virgin Islands British",
  VI = "Virgin Islands US",
  WF = "Wallis And Futuna",
  EH = "Western Sahara",
  YE = "Yemen",
  ZM = "Zambia",
  ZW = "Zimbabwe",
}

export enum CountryCodes {
  "Afghanistan" = "af",
  "AlandIslands" = "ax",
  "Albania" = "al",
  "Algeria" = "dz",
  "American Samoa" = "as",
  "Andorra" = "ad",
  "Angola" = "ao",
  "Anguilla" = "ai",
  "Antarctica" = "aq",
  "Antigua and Barbuda" = "ag",
  "Argentina" = "ar",
  "Armenia" = "am",
  "Aruba" = "aw",
  "Australia" = "au",
  "Austria" = "at",
  "Azerbaijan" = "az",
  "Bahamas" = "bs",
  "Bahrain" = "bh",
  "Bangladesh" = "bd",
  "Barbados" = "bb",
  "Belarus" = "by",
  "Belgium" = "be",
  "Belize" = "bz",
  "Benin" = "bj",
  "Bermuda" = "bm",
  "Bhutan" = "bt",
  "Bolivia" = "bo",
  "Bosnia and Herzegovina" = "ba",
  "Botswana" = "bw",
  "Bouvet Island" = "bv",
  "Brazil" = "br",
  "British Indian Ocean Territory" = "io",
  "Brunei Darussalam" = "bn",
  "Bulgaria" = "bg",
  "Burkina Faso" = "bf",
  "Burundi" = "bi",
  "Cambodia" = "kh",
  "Cameroon" = "cm",
  "Canada" = "ca",
  "Cape Verde" = "cv",
  "Cayman Islands" = "ky",
  "Central African Republic" = "cf",
  "Chad" = "td",
  "Chile" = "cl",
  "China" = "cn",
  "Christmas Island" = "cx",
  "Cocos Keeling Islands" = "cc",
  "Colombia" = "co",
  "Comoros" = "km",
  "Congo" = "cg",
  "Congo Democratic Republic" = "cd",
  "Cook Islands" = "ck",
  "Costa Rica" = "cr",
  "CoteDIvoire" = "ci",
  "Croatia" = "hr",
  "Cuba" = "cu",
  "Curacao" = "cw",
  "Cyprus" = "cy",
  "Czech Republic" = "cz",
  "Denmark" = "dk",
  "Djibouti" = "dj",
  "Dominica" = "dm",
  "Dominican Republic" = "do",
  "Ecuador" = "ec",
  "Egypt" = "eg",
  "El Salvador" = "sv",
  "Equatorial Guinea" = "gq",
  "Eritrea" = "er",
  "Estonia" = "ee",
  "Ethiopia" = "et",
  "Falkland Islands" = "fk",
  "Faroe Islands" = "fo",
  "Fiji" = "fj",
  "Finland" = "fi",
  "France" = "fr",
  "French Guiana" = "gf",
  "French Polynesia" = "pf",
  "French Southern Territories" = "tf",
  "Gabon" = "ga",
  "Gambia" = "gm",
  "Georgia" = "ge",
  "Germany" = "de",
  "Ghana" = "gh",
  "Gibraltar" = "gi",
  "Greece" = "gr",
  "Greenland" = "gl",
  "Grenada" = "gd",
  "Guadeloupe" = "gp",
  "Guam" = "gu",
  "Guatemala" = "gt",
  "Guernsey" = "gg",
  "Guinea" = "gn",
  "Guinea Bissau" = "gw",
  "Guyana" = "gy",
  "Haiti" = "ht",
  "Heard Island Mcdonald Islands" = "hm",
  "Holy See Vatican City State" = "va",
  "Honduras" = "hn",
  "HongKong" = "hk",
  "Hungary" = "hu",
  "Iceland" = "is",
  "India" = "in",
  "Indonesia" = "id",
  "Iran" = "ir",
  "Iraq" = "iq",
  "Ireland" = "ie",
  "Isle Of Man" = "im",
  "Israel" = "il",
  "Italy" = "it",
  "Jamaica" = "jm",
  "Japan" = "jp",
  "Jersey" = "je",
  "Jordan" = "jo",
  "Kazakhstan" = "kz",
  "Kenya" = "ke",
  "Kiribati" = "ki",
  "Korea, Republic of" = "kr",
  "Korea, Democratic People's Republic of" = "kp",
  "Kuwait" = "kw",
  "Kyrgyzstan" = "kg",
  "Lao Peoples Democratic Republic" = "la",
  "Latvia" = "lv",
  "Lebanon" = "lb",
  "Lesotho" = "ls",
  "Liberia" = "lr",
  "Libyan Arab Jamahiriya" = "ly",
  "Liechtenstein" = "li",
  "Lithuania" = "lt",
  "Luxembourg" = "lu",
  "Macao" = "mo",
  "Madagascar" = "mg",
  "Malawi" = "mw",
  "Malaysia" = "my",
  "Maldives" = "mv",
  "Mali" = "ml",
  "Malta" = "mt",
  "Marshall Islands" = "mh",
  "Martinique" = "mq",
  "Mauritania" = "mr",
  "Mauritius" = "mu",
  "Mayotte" = "yt",
  "Mexico" = "mx",
  "Micronesia" = "fm",
  "Moldova" = "md",
  "Monaco" = "mc",
  "Mongolia" = "mn",
  "Montenegro" = "me",
  "Montserrat" = "ms",
  "Morocco" = "ma",
  "Mozambique" = "mz",
  "Myanmar" = "mm",
  "Namibia" = "na",
  "Nauru" = "nr",
  "Nepal" = "np",
  "Netherlands" = "nl",
  "New Caledonia" = "nc",
  "New Zealand" = "nz",
  "Nicaragua" = "ni",
  "Niger" = "ne",
  "Nigeria" = "ng",
  "Niue" = "nu",
  "Norfolk Island" = "nf",
  "Northern Mariana Islands" = "mp",
  "Norway" = "no",
  "Oman" = "om",
  "Pakistan" = "pk",
  "Palau" = "pw",
  "Palestinian Territory" = "ps",
  "Panama" = "pa",
  "Papua New Guinea" = "pg",
  "Paraguay" = "py",
  "Peru" = "pe",
  "Philippines" = "ph",
  "Pitcairn" = "pn",
  "Poland" = "pl",
  "Portugal" = "pt",
  "Puerto Rico" = "pr",
  "Qatar" = "qa",
  "Reunion" = "re",
  "Republic of North Macedonia" = "mkd",
  "Romania" = "ro",
  "Russian Federation" = "ru",
  "Rwanda" = "rw",
  "Saint Barthelemy" = "bl",
  "Saint Helena" = "sh",
  "Saint Kitts And Nevis" = "kn",
  "Saint Lucia" = "lc",
  "Saint Martin" = "mf",
  "Saint Pierre And Miquelon" = "pm",
  "Saint Vincent And Grenadines" = "vc",
  "Samoa" = "ws",
  "San Marino" = "sm",
  "Sao Tome And Principe" = "st",
  "Saudi Arabia" = "sa",
  "Senegal" = "sn",
  "Serbia" = "rs",
  "Seychelles" = "sc",
  "Sierra Leone" = "sl",
  "Singapore" = "sg",
  "Slovakia" = "sk",
  "Slovenia" = "si",
  "Solomon Islands" = "sb",
  "Somalia" = "so",
  "South Africa" = "za",
  "South Georgia And Sandwich Island" = "gs",
  "Spain" = "es",
  "Sri Lanka" = "lk",
  "Sudan" = "sd",
  "South Sudan" = "ss",
  "Suriname" = "sr",
  "Svalbard And Jan Mayen" = "sj",
  "Swaziland" = "sz",
  "Sweden" = "se",
  "Switzerland" = "ch",
  "Sint Maarten (Dutch part" = "sx",
  "Syrian Arab Republic" = "sy",
  "Taiwan" = "tw",
  "Tajikistan" = "tj",
  "Tanzania" = "tz",
  "Thailand" = "th",
  "TimorLeste" = "tl",
  "Togo" = "tg",
  "Tokelau" = "tk",
  "Tonga" = "to",
  "Trinidad And Tobago" = "tt",
  "Tunisia" = "tn",
  "Turkey" = "tr",
  "Turkmenistan" = "tm",
  "Turks And Caicos Islands" = "tc",
  "Tuvalu" = "tv",
  "Uganda" = "ug",
  "Ukraine" = "ua",
  "United Arab Emirates" = "ae",
  "United Kingdom" = "gb",
  "United States" = "us",
  "United States Outlying Islands" = "um",
  "Uruguay" = "uy",
  "Uzbekistan" = "uz",
  "Vanuatu" = "vu",
  "Venezuela" = "ve",
  "Vietnam" = "vn",
  "Virgin Islands British" = "vg",
  "Virgin Islands US" = "vi",
  "Wallis And Futuna" = "wf",
  "Western Sahara" = "eh",
  "Yemen" = "ye",
  "Zambia" = "zm",
  "Zimbabwe" = "zw",
}

export const COUNTRIES = [
  {label: "Afghanistan", value: "af"},
  {label: "AlandIslands", value: "ax"},
  {label: "Albania", value: "al"},
  {label: "Algeria", value: "dz"},
  {label: "American Samoa", value: "as"},
  {label: "Andorra", value: "ad"},
  {label: "Angola", value: "ao"},
  {label: "Anguilla", value: "ai"},
  {label: "Antarctica", value: "aq"},
  {label: "Antigua and Barbuda", value: "ag"},
  {label: "Argentina", value: "ar"},
  {label: "Armenia", value: "am"},
  {label: "Aruba", value: "aw"},
  {label: "Australia", value: "au"},
  {label: "Austria", value: "at"},
  {label: "Azerbaijan", value: "az"},
  {label: "Bahamas", value: "bs"},
  {label: "Bahrain", value: "bh"},
  {label: "Bangladesh", value: "bd"},
  {label: "Barbados", value: "bb"},
  {label: "Belarus", value: "by"},
  {label: "Belgium", value: "be"},
  {label: "Belize", value: "bz"},
  {label: "Benin", value: "bj"},
  {label: "Bermuda", value: "bm"},
  {label: "Bhutan", value: "bt"},
  {label: "Bolivia", value: "bo"},
  {label: "Bosnia and Herzegovina", value: "ba"},
  {label: "Botswana", value: "bw"},
  {label: "Bouvet Island", value: "bv"},
  {label: "Brazil", value: "br"},
  {label: "British Indian Ocean Territory", value: "io"},
  {label: "Brunei Darussalam", value: "bn"},
  {label: "Bulgaria", value: "bg"},
  {label: "Burkina Faso", value: "bf"},
  {label: "Burundi", value: "bi"},
  {label: "Cambodia", value: "kh"},
  {label: "Cameroon", value: "cm"},
  {label: "Canada", value: "ca"},
  {label: "Cape Verde", value: "cv"},
  {label: "Cayman Islands", value: "ky"},
  {label: "Central African Republic", value: "cf"},
  {label: "Chad", value: "td"},
  {label: "Chile", value: "cl"},
  {label: "China", value: "cn"},
  {label: "Christmas Island", value: "cx"},
  {label: "Cocos Keeling Islands", value: "cc"},
  {label: "Colombia", value: "co"},
  {label: "Comoros", value: "km"},
  {label: "Congo", value: "cg"},
  {label: "Congo Democratic Republic", value: "cd"},
  {label: "Cook Islands", value: "ck"},
  {label: "Costa Rica", value: "cr"},
  {label: "CoteDIvoire", value: "ci"},
  {label: "Croatia", value: "hr"},
  {label: "Cuba", value: "cu"},
  {label: "Curaçao", value: "cw"},
  {label: "Cyprus", value: "cy"},
  {label: "Czech Republic", value: "cz"},
  {label: "Denmark", value: "dk"},
  {label: "Djibouti", value: "dj"},
  {label: "Dominica", value: "dm"},
  {label: "Dominican Republic", value: "do"},
  {label: "Ecuador", value: "ec"},
  {label: "Egypt", value: "eg"},
  {label: "El Salvador", value: "sv"},
  {label: "Equatorial Guinea", value: "gq"},
  {label: "Eritrea", value: "er"},
  {label: "Estonia", value: "ee"},
  {label: "Ethiopia", value: "et"},
  {label: "Falkland Islands", value: "fk"},
  {label: "Faroe Islands", value: "fo"},
  {label: "Fiji", value: "fj"},
  {label: "Finland", value: "fi"},
  {label: "France", value: "fr"},
  {label: "French Guiana", value: "gf"},
  {label: "French Polynesia", value: "pf"},
  {label: "French Southern Territories", value: "tf"},
  {label: "Gabon", value: "ga"},
  {label: "Gambia", value: "gm"},
  {label: "Georgia", value: "ge"},
  {label: "Germany", value: "de"},
  {label: "Ghana", value: "gh"},
  {label: "Gibraltar", value: "gi"},
  {label: "Greece", value: "gr"},
  {label: "Greenland", value: "gl"},
  {label: "Grenada", value: "gd"},
  {label: "Guadeloupe", value: "gp"},
  {label: "Guam", value: "gu"},
  {label: "Guatemala", value: "gt"},
  {label: "Guernsey", value: "gg"},
  {label: "Guinea", value: "gn"},
  {label: "Guinea Bissau", value: "gw"},
  {label: "Guyana", value: "gy"},
  {label: "Haiti", value: "ht"},
  {label: "Heard Island Mcdonald Islands", value: "hm"},
  {label: "Holy See Vatican City State", value: "va"},
  {label: "Honduras", value: "hn"},
  {label: "HongKong", value: "hk"},
  {label: "Hungary", value: "hu"},
  {label: "Iceland", value: "is"},
  {label: "India", value: "in"},
  {label: "Indonesia", value: "id"},
  {label: "Iran", value: "ir"},
  {label: "Iraq", value: "iq"},
  {label: "Ireland", value: "ie"},
  {label: "Isle Of Man", value: "im"},
  {label: "Israel", value: "il"},
  {label: "Italy", value: "it"},
  {label: "Jamaica", value: "jm"},
  {label: "Japan", value: "jp"},
  {label: "Jersey", value: "je"},
  {label: "Jordan", value: "jo"},
  {label: "Kazakhstan", value: "kz"},
  {label: "Kenya", value: "ke"},
  {label: "Kiribati", value: "ki"},
  {label: "Korea, Republic of", value: "kr"},
  {label: "Korea, Democratic People's Republic of", value: "kp"},
  {label: "Kuwait", value: "kw"},
  {label: "Kyrgyzstan", value: "kg"},
  {label: "Lao Peoples Democratic Republic", value: "la"},
  {label: "Latvia", value: "lv"},
  {label: "Lebanon", value: "lb"},
  {label: "Lesotho", value: "ls"},
  {label: "Liberia", value: "lr"},
  {label: "Libyan Arab Jamahiriya", value: "ly"},
  {label: "Liechtenstein", value: "li"},
  {label: "Lithuania", value: "lt"},
  {label: "Luxembourg", value: "lu"},
  {label: "Macao", value: "mo"},
  {label: "Madagascar", value: "mg"},
  {label: "Malawi", value: "mw"},
  {label: "Malaysia", value: "my"},
  {label: "Maldives", value: "mv"},
  {label: "Mali", value: "ml"},
  {label: "Malta", value: "mt"},
  {label: "Marshall Islands", value: "mh"},
  {label: "Martinique", value: "mq"},
  {label: "Mauritania", value: "mr"},
  {label: "Mauritius", value: "mu"},
  {label: "Mayotte", value: "yt"},
  {label: "Mexico", value: "mx"},
  {label: "Micronesia", value: "fm"},
  {label: "Moldova", value: "md"},
  {label: "Monaco", value: "mc"},
  {label: "Mongolia", value: "mn"},
  {label: "Montenegro", value: "me"},
  {label: "Montserrat", value: "ms"},
  {label: "Morocco", value: "ma"},
  {label: "Mozambique", value: "mz"},
  {label: "Myanmar", value: "mm"},
  {label: "Namibia", value: "na"},
  {label: "Nauru", value: "nr"},
  {label: "Nepal", value: "np"},
  {label: "Netherlands", value: "nl"},
  {label: "New Caledonia", value: "nc"},
  {label: "New Zealand", value: "nz"},
  {label: "Nicaragua", value: "ni"},
  {label: "Niger", value: "ne"},
  {label: "Nigeria", value: "ng"},
  {label: "Niue", value: "nu"},
  {label: "Norfolk Island", value: "nf"},
  {label: "Northern Mariana Islands", value: "mp"},
  {label: "Norway", value: "no"},
  {label: "Oman", value: "om"},
  {label: "Pakistan", value: "pk"},
  {label: "Palau", value: "pw"},
  {label: "Palestinian Territory", value: "ps"},
  {label: "Panama", value: "pa"},
  {label: "Papua New Guinea", value: "pg"},
  {label: "Paraguay", value: "py"},
  {label: "Peru", value: "pe"},
  {label: "Philippines", value: "ph"},
  {label: "Pitcairn", value: "pn"},
  {label: "Poland", value: "pl"},
  {label: "Portugal", value: "pt"},
  {label: "Puerto Rico", value: "pr"},
  {label: "Qatar", value: "qa"},
  {label: "Reunion", value: "re"},
  {label: "Republic of North Macedonia", value: "mkd"},
  {label: "Romania", value: "ro"},
  {label: "Russian Federation", value: "ru"},
  {label: "Rwanda", value: "rw"},
  {label: "Saint Barthelemy", value: "bl"},
  {label: "Saint Helena", value: "sh"},
  {label: "Saint Kitts And Nevis", value: "kn"},
  {label: "Saint Lucia", value: "lc"},
  {label: "Saint Martin", value: "mf"},
  {label: "Saint Pierre And Miquelon", value: "pm"},
  {label: "Saint Vincent And Grenadines", value: "vc"},
  {label: "Samoa", value: "ws"},
  {label: "San Marino", value: "sm"},
  {label: "Sao Tome And Principe", value: "st"},
  {label: "Saudi Arabia", value: "sa"},
  {label: "Senegal", value: "sn"},
  {label: "Serbia", value: "rs"},
  {label: "Seychelles", value: "sc"},
  {label: "Sierra Leone", value: "sl"},
  {label: "Singapore", value: "sg"},
  {label: "Slovakia", value: "sk"},
  {label: "Slovenia", value: "si"},
  {label: "Solomon Islands", value: "sb"},
  {label: "Somalia", value: "so"},
  {label: "South Africa", value: "za"},
  {label: "South Georgia And Sandwich Island", value: "gs"},
  {label: "Spain", value: "es"},
  {label: "Sri Lanka", value: "lk"},
  {label: "Sudan", value: "sd"},
  {label: "South Sudan", value: "ss"},
  {label: "Suriname", value: "sr"},
  {label: "Svalbard And Jan Mayen", value: "sj"},
  {label: "Swaziland", value: "sz"},
  {label: "Sweden", value: "se"},
  {label: "Switzerland", value: "ch"},
  {label: "Sint Maarten (Dutch part", value: "sx"},
  {label: "Syrian Arab Republic", value: "sy"},
  {label: "Taiwan", value: "tw"},
  {label: "Tajikistan", value: "tj"},
  {label: "Tanzania", value: "tz"},
  {label: "Thailand", value: "th"},
  {label: "TimorLeste", value: "tl"},
  {label: "Togo", value: "tg"},
  {label: "Tokelau", value: "tk"},
  {label: "Tonga", value: "to"},
  {label: "Trinidad And Tobago", value: "tt"},
  {label: "Tunisia", value: "tn"},
  {label: "Turkey", value: "tr"},
  {label: "Turkmenistan", value: "tm"},
  {label: "Turks And Caicos Islands", value: "tc"},
  {label: "Tuvalu", value: "tv"},
  {label: "Uganda", value: "ug"},
  {label: "Ukraine", value: "ua"},
  {label: "United Arab Emirates", value: "ae"},
  {label: "United Kingdom", value: "gb"},
  {label: "United States", value: "us"},
  {label: "United States Outlying Islands", value: "um"},
  {label: "Uruguay", value: "uy"},
  {label: "Uzbekistan", value: "uz"},
  {label: "Vanuatu", value: "vu"},
  {label:  "Venezuela", value: "ve"},
  {label:  "Vietnam", value: "vn"},
  {label: "Virgin Islands British", value: "vg"},
  {label: "Virgin Islands US", value: "vi"},
  {label: "Wallis And Futuna", value: "wf"},
  {label:  "Western Sahara", value: "eh"},
  {label: "Yemen", value: "ye"},
  {label: "Zambia", value: "zm"},
  {label: "Zimbabwe", value: "zw"}
];



export type Country = keyof typeof CountryCodes;

export type CountryCodeType = typeof CountryCodes[keyof typeof CountryCodes];

export const countryCodesArray = COUNTRIES.map(item => item.value) as CountryCodes[];
