export const OrderHints = {
    date: 'When the order was created',
    preferredDeliveryDate: 'When the order should be delivered',
    clientOrderID: 'Order number in your system',
    preferredWarehouse: 'The warehouse from which the parcel should be sent',
    preferredWarehouseMandatory: 'Switch on if this warehouse should be chosen in any case. If not mandatory and there is no stock at chosen warehouse, the system will choose another warehouse where the stock is enough',
    preferredCourierService: 'The courier service by which the parcel should be sent',
    preferredCourierServiceMandatory: 'Switch on if this courier service should be chosen in any case. If not mandatory, the system will choose a courier service according to the internal algorithm',

    //order products
    codCurrency: 'The currency in which the customer will pay the amount of the cash on delivery',
    priceCurrency: 'The currency of initial order',
    selection: 'Click here to choose multiple products for the order',
    // addProduct: 'Add a product to the order one by one',
    // removeSelected: 'Delete a chosen product',

    files: 'Any files related to the order (e.g., invoice or return form)',

    //address
    country: 'Country of the customer',
    county: 'County / district / municipio / prefecture-level area',
    county_district: 'County / district / municipio / prefecture-level area',
    state_region: 'State / region / province / prefecture / territory',
    city: 'Name of the city',
    city_subdivision: 'Borough / sector / delegación / ward',
    locality: 'Smaller neighborhood or local administrative unit',
    street: 'Street, avenue, block, or road name',
    street_number: 'House/building number',
    block_lot: 'Block, lot, land parcel, sub-block',
    building: 'Building, tower, complex, corporate building, section',
    unit: 'Apartment, office, suite, room, or floor',
    landmark: 'Useful in regions with poor addressing systems',
    details: 'Additional instructions: entrance details, delivery notes, references, company name, etc',
    coordinates: 'GPS coordinates of the exact delivery point',
    fullName: 'Full name of the customer',
    phone: 'Customer\'s phone number',
    email: 'Customer\'s email address',
    zipCode: 'Customer\'s zipcode',
    address: 'Street, building, apartment, etc. Recommended length - maximum 60 characters (depending on courier service)',
}